default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 0.0.0.0
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: latamgateway_cep_api_dev

test:
  <<: *default
  database: latamgateway_cep_api_test

production:
  <<: *default
  database: latamgateway_cep_api